### ISSUE TITLE
Orphaned resources for integration tests

### ISSUE THREAD

**Issue by henrytk** [alphagov/paas-s3-broker#4]
The integration tests do nothing to try and clear up orphaned resources if there is a test failure.

**Comment by henrytk** [comment]
Hi @tnwhitwell, could you record why this was closed please? i.e. no priority to fix, already fixed et cetera. Same goes for the other issue regarding flakey tests.

**Comment by tnwhitwell** [comment]
Sure: [we're now clearing up the created resources with `defer`s](https://github.com/alphagov/paas-s3-broker/compare/e65d44871e81e217435fcec4318ec2d216b1af18...master#diff-354f30a63fb0907d4ad57269548329e3) - completed in #7, #8 and #10. Integration tests were run during development with ~some~ many failures, and all resources were cleaned up each time
